<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Código para restablecer contraseña</title>        
    </head>
    <body>
        <table class="tbl" bgcolor="#FFFFFF" cellspacing="0" cellpadding="0" border="0" align="center" style=" height: 97px; max-width: 600px; width: 100%; border:6px solid #649ED3; border-bottom: 0; ">
            <tr>
                <td style=" font-family: arial;background-color: #FFF; padding: 20px 0px;" align="center">
                    <span style="color: #004B83; font-weight: bold; font-size: 28px; max-width: 390px; line-height: 40px; padding: 0 0 0 15px; " class="title">
                        Iké</span>          
                    </span>
                    <span style="color: #649ED3; font-size: 28px; max-width: 390px; line-height: 40px; padding: 0 15px 0 0; " class="title">
                        Sitio encuestador</span>          
                    </span>
                </td>
            </tr>
        </table>
        <table class="tbl" bgcolor="#FFF" cellspacing="0" cellpadding="0" border="0" align="center" style="table-layout: fixed; max-width: 600px; width: 100%; border:6px solid #649ED3; border-top: 0px; font-family: arial;  background-position: no-repeat; background-size: cover;">      
        <tr>
            <td  style="font-family: arial; padding: 0;
                ">
                <br>
                <span style="color: #004B83; font-weight: bold; font-size: 20px; max-width: 390px; line-height: 40px; padding: 0 15px 0 15px; display: block;" class="title">
                    ¿Olvidaste tu contraseña?</span>          
                </span>
                <br>
                <span style="color: #000000; font-weight: bold; font-size: 14px; margin: 0px 20px 0px 20px;  display: block; line-height: 20px;" class="title">
                    Ingresa a la siguiente liga para reestablecer tu contraseña:        
                </span>
                <br><br>
                <span style="color: #000000; font-weight: bold; font-size: 28px; margin: 0px 20px 0px 20px; display: block; line-height: 30px;" class="title">
                    <a href="${linkVar}" style="color: #004B83; font-weight: bold; font-size: 20px; max-width: 390px; line-height: 40px; padding: 0 15px 0 15px; display: block;" class="title">Reestablece tu contraseña</a>
                </span>
                <br><br>
                <span style="color: #000000; font-weight: bold; font-size: 14px; margin: 0px 20px 0px 20px; max-width: 500px; display: block; line-height: 20px;" class="title">
                    Si no solicitaste reestablecer tu contraseña o crees que tus datos están siendo usados sin tu autorización, ignora este correo.    
                </span>
                <br><br>
            </td>
        </tr>
        </table>
    </body>
</html>