<html  lang="es">
<head>
	<title>Banorte</title>
	<style type="text/css">
.Legales {
	font-size: 10px;
	font-style: normal;
	font-weight: normal;
	color: #4d4d4f;
	font-family: Arial, Helvetica, sans-serif;
	text-align: justify;

} 
.Apreciable {
    font-size: 16px;
    font-style: normal;
    font-weight: normal;
    color: #4d4d4f;
    font-family: Arial, Helvetica, sans-serif;
    align-text: left;
    padding-left: 30px;
}
.Copy_Legales {
	font-size: 12px;
	font-style: normal;
	font-weight: normal;
	color: #404040;
	font-family: Arial, Helvetica, sans-serif;
	text-align: justify;
} 
.Copy_1 {
	font-size: 16px;
	font-style: normal;
	font-weight: normal;
	color: #4d4d4f;
	font-family: Arial, Helvetica, sans-serif;
	text-align: justify;
	padding-left: 40px;
	padding-right: 40px;
} 
.Copy_left {
	font-size: 16px;
	font-style: normal;
	font-weight: bold;
	color: #4d4d4f;
	font-family: Arial, Helvetica, sans-serif;
	text-align: left;
} 
.Copy_2 {
	font-size: 16px;
	font-style: normal;
	font-weight: bold;
	color: #ea002a;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
} 
.Copy_3 {
	font-size: 16px;
	font-style: normal;
	font-weight: normal;
	color: #154734;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
} 
.Copy_4 {
	font-size: 14px;
	font-style: normal;
	font-weight: normal;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
	color: #FFFFFF;
	background-color: #ea002a;
	padding:10px;
	width:150px;
	border-radius:5px;
} 
.Vigencia {
	font-size: 16px;
	font-style: normal;
	font-weight: normal;
	color: #4d4d4f;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
} 
.El_Banco_Fuerte {
	font-size: 32px;
	font-style: normal;
	font-weight: bold;
	color: #ea002a;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
} 
.Copy_5 {
	font-size: 40px;
	font-style: normal;
	font-weight: bold;
	color: #154734;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
} 
.Titulo_1 {
	font-size: 23px;
	font-style: normal;
	font-weight: normal;
	color: #4d4d4f;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
} 
.Titulo_2 {
    font-size: 23px;
    font-style: normal;
    font-weight: bold;
    color: #cea800;
    font-family: Arial, Helvetica, sans-serif;
    text-align: center;
} 
.Titulo_United {
	font-size: 23px;
	font-style: normal;
	font-weight: bold;
	color: #223643;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
	padding-bottom: 20px;
} 
.Titulo_4 {
	font-size: 23px;
	font-style: normal;
	font-weight: bold;
	color: #ea002a;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
} 
.Titulo_Big_1 {
	font-size: 17px;
	font-style: normal;
	font-weight: bold;
	color: #4d4d4f;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
} 
.Titulo_Big_2 {
	font-size: 36px;
	font-style: normal;
	font-weight: bold;
	color: #FFFFFF;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
} 
.Titulo_Big_3 {
	font-size: 54px;
	font-style: normal;
	font-weight: bold;
	color: #FFFFFF;
	font-family: Arial, Helvetica, sans-serif;
	text-align: center;
} 
.CAT {
	font-size: 18px;
	font-style: normal;
	font-weight: bold;
	color: #4d4d4f;
	font-family: Arial, Helvetica, sans-serif;
	text-align: justify;
}
.linea_legal {
	background-color: rgb(204, 204, 204);
    height: 1px;
}
    body {
	margin-top: 0px;
	text-align: center;
	margin-left: 0px;
	margin-right: 0px;
}
    </style>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
      <th height="49" bgcolor="#ea002a" scope="col"><img src="http://gecco.com.mx/Banorte/Mailings/legales/pleca_banorte.jpg" width="650" height="49" alt=""/></th>
    </tr>
  </tbody>
</table>
<br>
<table align="center" border="0" cellpadding="0" cellspacing="0" width="650">
	<tbody>
		<tr>
		  <td colspan="3" align="center" class="linea_legal"><a style="height:1px;"></a></td>
	  </tr>
		<tr>
		  <td width="80" align="center"><img src="http://gecco.com.mx/Banorte/Mailings/legales/mail_banorte_icon.jpg" width="80" height="62" alt=""/></td>
		  <td width="20" align="center">&nbsp;</td>
		  <td width="550" height="100" align="center" class="Copy_Legales"><strong>BANORTE NUNCA</strong> solicita v&iacute;a correo o llamada telef&oacute;nica tu informaci&oacute;n confidencial como: <em>Usuario, Contrase&ntilde;a, Token, NIP, No. Cuenta, No. Tarjeta o No. Seguridad.</em><br>
	      <strong>BANORTE NUNCA </strong>solicita que descargues y/o abras archivos, ni que accedas directamente a ligas (URL's) haciendo clic en ellas.<br>
          <strong>BANORTE NUNCA</strong> solicita llamar a n&uacute;meros desconocidos.</td>
      </tr>
		<tr>
		  <td colspan="3" align="center" class="linea_legal"><a style="height:1px;"></a></td>
	  </tr>
		<tr>
		  <td height="40" colspan="3" align="center"><span class="Legales">Si usted no visualiza bien este mail, <a href="#!vistamail3!#"><font color="#000000">haga click aqu&iacute;</font></a></span></td>
	  </tr>
		<tr>
		  <td height="160" colspan="3" align="left"><p><img src="https://gecco.com.mx/banorte/mailings/2021/noviembre/B_asistencias_banorte_bienvenida_1/B_asistencias_banorte_bienvenida_1_01.jpg" width="650" height="466" alt=""/></p>
	      <p class="Apreciable">${name}</p>
	      <p><img src="https://gecco.com.mx/banorte/mailings/2021/noviembre/line.jpg" width="650" height="29" alt=""/></p>
	      <p><img src="https://gecco.com.mx/banorte/mailings/2021/noviembre/B_asistencias_banorte_bienvenida_1/B_asistencias_banorte_bienvenida_1_02.jpg" width="650" height="1312" alt=""/></p></td>
	  </tr>
	</tbody>
</table>
</body>
</html>